spring:
  datasource:
    url: jdbc:oracle:thin:@dbname_alias?TNS_ADMIN=/Users/test/wallet/wallet_dbname_alias
    username: FERCAN
    password: ValleGrande2022
    driver-class-name: oracle.jdbc.OracleDriver
    type: oracle.ucp.jdbc.PoolDataSource
    oracleucp:
      connection-factory-class-name: oracle.jdbc.pool.OracleDataSource
      connection-pool-name: connectionPoolName1
      min-pool-size: 10
      max-pool-size: 10